name: CI
on:
  push:
    branches: [ master ]
    paths:
      - .github/workflows/main.yml
  pull_request:
    branches: [ master ]
    paths:
      - .github/workflows/main.yml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $FOO
        env:
          FOO: A
          BAR: B
          FOO: C
