name: CI2
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: echo $FOO
        env:
          FOO: A
          BAR: B
